/*
    ============================================================
    Treasure Chest - OpenGL

    Author: Leonardo Moura
    Date: 2026

    Description:

    This class is responsible for loading and managing a 2D texture
    using the stb_image library and the OpenGL texture API.

    The class performs the complete texture initialization process,
    including image loading, texture creation, parameter configuration,
    mipmap generation, and resource cleanup.

    During construction, the image file is loaded from disk, uploaded
    to the GPU, and configured for rendering. Once created, the texture
    can be bound to any texture unit and used by GLSL shaders.

    Responsibilities:

        • Load image files from disk
        • Create an OpenGL texture object
        • Upload image data to GPU memory
        • Configure wrapping modes
        • Configure texture filtering
        • Generate mipmaps automatically
        • Bind and unbind textures
        • Release GPU resources when destroyed

    Technologies:

        • OpenGL 3.3 Core Profile
        • stb_image
        • GLEW
        • C++

    Learning Topics:

        • Texture Mapping
        • GPU Resource Management
        • Texture Units
        • Mipmapping
        • Image Loading
        • Texture Filtering
        • Texture Wrapping

    ============================================================
*/

#pragma once

#include <string>

#include <glew.h>

class Texture
{
public:

    // OpenGL texture handle.
    // This identifier is generated by OpenGL and uniquely
    // represents the texture stored in GPU memory.
    GLuint ID;

    // Constructor.
    // Loads an image from disk, creates the OpenGL texture,
    // uploads the pixel data to the GPU, and generates mipmaps.
    Texture(const char* path);

    // Destructor.
    // Automatically releases the OpenGL texture from GPU memory.
    ~Texture();

    // Binds the texture to the specified texture unit.
    // By default, the texture is bound to GL_TEXTURE0.
    void Bind(GLuint unit = 0) const;

    // Unbinds the current texture from GL_TEXTURE_2D.
    void Unbind() const;

private:

    // Image width in pixels.
    int width;

    // Image height in pixels.
    int height;

    // Number of color channels contained in the image.
    // Examples:
    // 1 = Grayscale
    // 3 = RGB
    // 4 = RGBA
    int channels;
};