/*
    ============================================================
    Fragment Shader - OpenGL

    Author: Leonardo Moura
    Date: 2026

    Description:

    This Fragment Shader is responsible for determining the
    final color of every pixel generated by the rasterizer.

    For each fragment, the shader samples the texture using
    the interpolated texture coordinates received from the
    Vertex Shader.

    The sampled color becomes the final color written to the
    framebuffer.

    Responsibilities:

        • Receive interpolated texture coordinates
        • Sample a 2D texture
        • Output the final fragment color

    OpenGL Pipeline:

        Vertex Shader
              ↓
        Primitive Assembly
              ↓
        Rasterization
              ↓
        Fragment Shader   ← This stage
              ↓
        Framebuffer

    Learning Topics:

        • GLSL Fragment Shaders
        • Texture Sampling
        • UV Coordinates
        • Sampler2D
        • Rasterization
        • Framebuffer Output

    ============================================================
*/

#version 330 core

//--------------------------------------------------------------
// Interpolated texture coordinates coming from the Vertex Shader.
// Every fragment receives its own UV coordinate.
//--------------------------------------------------------------
in vec2 TexCoord;

//--------------------------------------------------------------
// Final color written to the framebuffer.
//--------------------------------------------------------------
out vec4 FragColor;

//--------------------------------------------------------------
// 2D texture containing the treasure chest image.
//
// This texture is bound from the C++ application using:
//
// shader.SetInt("texture1", 0);
//--------------------------------------------------------------
uniform sampler2D texture1;

void main()
{
    //----------------------------------------------------------
    // Sample the texture using the interpolated UV coordinates
    // and output the resulting color.
    //----------------------------------------------------------

    FragColor = texture(texture1, TexCoord);
}